config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'videos/index'
  devise_for :users
  root to: "videos#index"

  resources :videos 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
    self.data = [
      { id: 1, name: '--' },
      { id: 2, name: '音楽' },
      { id: 3, name: '料理' },
      { id: 4, name: 'ビジネス' },
      { id: 5, name: 'エンタメ' },
      { id: 6, name: 'スポーツ' },
      { id: 7, name: 'ゲーム' },
      { id: 8, name: 'vlog' }
    ]
end

app/models/post.rb
class Post < ApplicationRecord
  # mount_uploader :video, VideoUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :videos
  
  with_options presence: true do
    validates :nickname
    validates :email
    validates :password, format: { with: /\A[a-z0-9]+\z/i }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
    validates :kana_last_name, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :kana_first_name, format: { with: /\A[ァ-ヶー－]+\z/ }
    validates :birthday
   end 

end

app/models/video.rb
class Video < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  mount_uploader :video, VideoUploader
  belongs_to_active_hash :category
  belongs_to :user
  has_one_attached :image
  has_one_attached :video
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name, :kana_last_name, :kana_first_name, :birthday])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:video)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :move_to_sign_in, except: [:index, :show, :new, :create]

  def index
    @video = Video.order("created_at DESC")
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(create_params)

    if @video.save
      redirect_to root_path
   else
     render :new
   end
  end
 

  def destroy
  end

  private
  def create_params
  params.required(:video).permit(:name, :video, :explanation, :category_id, :image, :price).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZERO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.video %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Video:</strong>
  <%= link_to @post.video_url.to_s do %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='login_fotter'>
</div>

app/views/shared/_header.html.erb
<div class="title"> タイトル
</div>
　　　
<div class="search" >
<div class="form-input">
    <input class="form-word" placeholder= "検索">
  </div>
  <input class="form-submit" type="submit" value="🔍">
</div>
     
<ul class='lists-right'>
  <li><%= link_to '投稿', new_video_path, class: "post"%>
    <% if user_signed_in? %>
       <li><%= link_to current_user.nickname, "#", class: "user-nickname"  %></li>
       <li><%= link_to 'ログアウト', "/users/sign_out", method: :delete, class: "logout"  %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', "/users/sign_up", class: "sign-up" %></li>
    <% end %>
</ul>
   

app/views/shared/_second-header.html.erb
<div class='login_title'>
<%= link_to "ZERO" "/" %>
 </div>

app/views/shared/_side-bar.html.erb
<div class="category">
  <%= "カテゴリー" %>
  <ul class='category_list'>
  <li class='music'>
  <%= "音楽"%>
  <li class='cook'>
  <%= "料理"%>
  <li class='business'>
  <%= "ビジネス"%>
  <li class='entertainment'>
  <%= "エンターテイメント"%>
  <li class='sport'>
  <%= "スポーツ"%>
  <li class='game'>
  <%= "ゲーム"%>
  <li class='vlog'>
  <%= "vlog"%>
</div>

app/views/videos/index.html.erb
<div class="top">
<%= render "shared/header" %>
</div>

<div class="main_items">
<%= render "shared/side-bar" %> 
 
 <div class="videos">
  <%= "投稿ビデオ" %>
    <% @video.each do |video|%>
    <li class='list'>
      <%= link_to video_path(video.id) do %>
      <div class='item-img-content'>
      <%= image_tag video.image.variant(resize:'500x500'), class: 'message-image' if video.image.attached?%> 
       <% end %>
    <% end %>
  
  <ul class='main_category_list'>
  <li class='main_music'>
  <%= "音楽"%>
  <li class='main_cook'>
  <%= "料理"%>
  <li class='main_business'>
  <%= "ビジネス"%>
  <li class='main_entertainment'>
  <%= "エンターテイメント"%>
  <li class='main_sport'>
  <%= "スポーツ"%>
  <li class='main_game'>
  <%= "ゲーム"%>
  <li class='main_vlog'>
  <%= "vlog"%>

</div>


<%# <h1>Videos#index</h1>
<p>Find me in app/views/videos/index.html.erb</p> %>

app/views/videos/new.html.erb
<header class="post_top">
<%="投稿ページ"%>
</header>
<%= form_with model: @video, local: true do |f| %>
<div class="video-title">タイトル
 <div class="new-items">
      <div class="weight-bold-text">
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
    </div>
</div>

<div class="movie">動画投稿
<div class="img-upload">
      <div class="weight-bold-text">
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :video, id:"item-video" %>
      </div>
    </div>
</div>

<div class="expalanation">動画説明
 <div class="items-explain">
        <div class="weight-bold-text">
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"explanation", placeholder:"商品の説明" ,rows:"7" ,maxlength:"1000" %>
      </div>
</div>

<div class="video-category">カテゴリー
<%= f.collection_select(:category_id, Category.all, :id, :name, {class:"select-box", id:"item-category"}) %>
</div>

<div class="thumbnail">サムネイル
<div class="img-upload">
      <div class="weight-bold-text">
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
</div>

<div class="price">価格
　</div>
  <span class="sell-yen">¥</span>
  <%= f.text_field :price, class:"price-input", id:"price", placeholder:"例）" %>
  </div>
</div>

<div class="post-btn-contents">
<%= f.submit "投稿する" ,class:"post-btn" %> 
<%=link_to 'もどる', root_path, class:"back-btn" %>
</div>
<% end %>